@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class FrAssignedAuthor{

             AssignedAuthor => [None..None]
             AssignedAuthor.nullFlavor => [None..0]
             AssignedAuthor.typeId.nullFlavor => [None..0]
             AssignedAuthor.typeId.assigningAuthorityName => [None..0]
             AssignedAuthor.typeId.displayable => [None..0]
             AssignedAuthor.classCode => [None..0]
             AssignedAuthor.id.nullFlavor => [None..0]
             AssignedAuthor.sdtcIdentifiedBy => [None..0]
             AssignedAuthor.code => [None..None]
             AssignedAuthor.assignedPerson => [None..None]
             AssignedAuthor.assignedAuthoringDevice => [None..None]
             AssignedAuthor.representedOrganization => [None..None]
        } 

        class FrAssignedCustodian{

             AssignedCustodian => [None..None]
             AssignedCustodian.typeId.nullFlavor => [None..0]
             AssignedCustodian.typeId.assigningAuthorityName => [None..0]
             AssignedCustodian.typeId.displayable => [None..0]
             AssignedCustodian.classCode => [None..0]
             AssignedCustodian.representedCustodianOrganization => [None..None]
        } 

        class FrAssignedEntity{

             AssignedEntity => [None..None]
             AssignedEntity.nullFlavor => [None..0]
             AssignedEntity.typeId.nullFlavor => [None..0]
             AssignedEntity.typeId.assigningAuthorityName => [None..0]
             AssignedEntity.typeId.displayable => [None..0]
             AssignedEntity.classCode => [None..0]
             AssignedEntity.id => [None..1]
             AssignedEntity.sdtcIdentifiedBy => [None..0]
             AssignedEntity.code.nullFlavor => [None..0]
             AssignedEntity.code.codeSystemVersion => [None..0]
             AssignedEntity.code.sdtcValueSet => [None..0]
             AssignedEntity.code.sdtcValueSetVersion => [None..0]
             AssignedEntity.assignedPerson => [None..None]
             AssignedEntity.representedOrganization => [None..None]
             AssignedEntity.sdtcPatient => [None..0]
        } 

        class FrAssociatedEntity{

             AssociatedEntity => [None..None]
             AssociatedEntity.nullFlavor => [None..0]
             AssociatedEntity.typeId.nullFlavor => [None..0]
             AssociatedEntity.typeId.assigningAuthorityName => [None..0]
             AssociatedEntity.typeId.displayable => [None..0]
             AssociatedEntity.sdtcIdentifiedBy => [None..0]
             AssociatedEntity.associatedPerson => [None..None]
             AssociatedEntity.scopingOrganization => [None..None]
        } 

        class FrAuthenticator{

             Authenticator => [None..None]
             Authenticator.nullFlavor => [None..0]
             Authenticator.typeId.nullFlavor => [None..0]
             Authenticator.typeId.assigningAuthorityName => [None..0]
             Authenticator.typeId.displayable => [None..0]
             Authenticator.typeCode => [None..0]
             Authenticator.time => [None..None]
             Authenticator.time.value => [None..None]
             Authenticator.signatureCode => [None..None]
             Authenticator.signatureCode.code => [None..None]
             Authenticator.signatureCode.sdtcValueSet => [None..0]
             Authenticator.signatureCode.sdtcValueSetVersion => [None..0]
             Authenticator.sdtcSignatureText => [None..0]
             Authenticator.assignedEntity => [None..None]
        } 

        class FrAuthor{

             Author => [None..None]
             Author.nullFlavor => [None..0]
             Author.typeId.nullFlavor => [None..0]
             Author.typeId.assigningAuthorityName => [None..0]
             Author.typeId.displayable => [None..0]
             Author.typeCode => [None..0]
             Author.contextControlCode => [None..0]
             Author.functionCode.nullFlavor => [None..0]
             Author.functionCode.code => [1..None]
             Author.functionCode.codeSystem => [1..None]
             Author.functionCode.codeSystemVersion => [None..0]
             Author.functionCode.sdtcValueSet => [None..0]
             Author.functionCode.sdtcValueSetVersion => [None..0]
             Author.time.value => [1..None]
             Author.assignedAuthor => [None..None]
        } 

        class FrAuthoringDevice{

             AuthoringDevice.typeId.nullFlavor => [None..0]
             AuthoringDevice.typeId.assigningAuthorityName => [None..0]
             AuthoringDevice.typeId.displayable => [None..0]
             AuthoringDevice.classCode => [None..0]
             AuthoringDevice.determinerCode => [None..0]
             AuthoringDevice.manufacturerModelName => [1..None]
             AuthoringDevice.softwareName => [1..None]
        } 

        class FrAuthorization{

             Authorization => [None..None]
             Authorization.typeId.nullFlavor => [None..0]
             Authorization.typeId.assigningAuthorityName => [None..0]
             Authorization.typeId.displayable => [None..0]
             Authorization.typeCode => [None..0]
             Authorization.consent => [None..None]
             Authorization.consent.id => [None..None]
             Authorization.consent.code => [None..None]
             Authorization.consent.statusCode.code => [None..None]
             Authorization.consent.statusCode.sdtcValueSet => [None..0]
             Authorization.consent.statusCode.sdtcValueSetVersion => [None..0]
        } 

        class FrComponentOf{

             ComponentOf => [None..None]
        } 

        class FrCustodian{

             Custodian => [None..None]
             Custodian.nullFlavor => [None..0]
             Custodian.typeId.nullFlavor => [None..0]
             Custodian.typeId.assigningAuthorityName => [None..0]
             Custodian.typeId.displayable => [None..0]
             Custodian.typeCode => [None..0]
             Custodian.assignedCustodian => [None..None]
        } 

        class FrDataEnterer{

             DataEnterer => [None..None]
             DataEnterer.nullFlavor => [None..0]
             DataEnterer.typeId.nullFlavor => [None..0]
             DataEnterer.typeId.assigningAuthorityName => [None..0]
             DataEnterer.typeId.displayable => [None..0]
             DataEnterer.typeCode => [None..0]
             DataEnterer.contextControlCode => [None..0]
             DataEnterer.time => [1..None]
             DataEnterer.assignedEntity => [None..None]
        } 

        class FrDocumentationOf{

             DocumentationOf => [None..None]
             DocumentationOf.nullFlavor => [None..0]
             DocumentationOf.typeId.nullFlavor => [None..0]
             DocumentationOf.typeId.assigningAuthorityName => [None..0]
             DocumentationOf.typeId.displayable => [None..0]
             DocumentationOf.typeCode => [None..0]
             DocumentationOf.serviceEvent => [None..None]
        } 

        class FrInFulfillmentOf{

             InFulfillmentOf => [None..None]
             InFulfillmentOf.typeId.nullFlavor => [None..0]
             InFulfillmentOf.typeId.assigningAuthorityName => [None..0]
             InFulfillmentOf.typeId.displayable => [None..0]
             InFulfillmentOf.typeCode => [None..0]
             InFulfillmentOf.order => [None..None]
        } 

        class FrInformant{

             Informant => [None..None]
             Informant.nullFlavor => [None..0]
             Informant.typeId.nullFlavor => [None..0]
             Informant.typeId.assigningAuthorityName => [None..0]
             Informant.typeId.displayable => [None..0]
             Informant.typeCode => [None..0]
             Informant.contextControlCode => [None..0]
             Informant.assignedEntity => [None..None]
             Informant.relatedEntity => [None..None]
        } 

        class FrInformationRecipient{

             InformationRecipient => [None..None]
             InformationRecipient.nullFlavor => [None..0]
             InformationRecipient.typeId.nullFlavor => [None..0]
             InformationRecipient.typeId.assigningAuthorityName => [None..0]
             InformationRecipient.typeId.displayable => [None..0]
             InformationRecipient.typeCode => [None..0]
             InformationRecipient.intendedRecipient => [None..None]
        } 

        class FrIntendedRecipient{

             IntendedRecipient.typeId.nullFlavor => [None..0]
             IntendedRecipient.typeId.assigningAuthorityName => [None..0]
             IntendedRecipient.typeId.displayable => [None..0]
             IntendedRecipient.classCode => [None..0]
             IntendedRecipient.id.assigningAuthorityName => [None..0]
             IntendedRecipient.id.displayable => [None..0]
             IntendedRecipient.id.root => [1..None]
             IntendedRecipient.id.extension => [1..None]
             IntendedRecipient.informationRecipient => [None..None]
             IntendedRecipient.receivedOrganization => [None..None]
             IntendedRecipient.receivedOrganization.id.assigningAuthorityName => [None..0]
             IntendedRecipient.receivedOrganization.id.displayable => [None..0]
             IntendedRecipient.receivedOrganization.id.root => [None..None]
        } 

        class FrLegalAuthenticator{

             LegalAuthenticator => [None..None]
             LegalAuthenticator.nullFlavor => [None..0]
             LegalAuthenticator.typeId.nullFlavor => [None..0]
             LegalAuthenticator.typeId.assigningAuthorityName => [None..0]
             LegalAuthenticator.typeId.displayable => [None..0]
             LegalAuthenticator.typeCode => [None..0]
             LegalAuthenticator.contextControlCode => [None..0]
             LegalAuthenticator.time => [None..None]
             LegalAuthenticator.time.value => [None..None]
             LegalAuthenticator.signatureCode => [None..None]
             LegalAuthenticator.signatureCode.code => [None..None]
             LegalAuthenticator.signatureCode.sdtcValueSet => [None..0]
             LegalAuthenticator.signatureCode.sdtcValueSetVersion => [None..0]
             LegalAuthenticator.sdtcSignatureText => [None..0]
             LegalAuthenticator.assignedEntity => [None..None]
             LegalAuthenticator.assignedEntity.code => [None..None]
        } 

        class FrOrder{

             Order.nullFlavor => [None..0]
             Order.typeId.nullFlavor => [None..0]
             Order.typeId.assigningAuthorityName => [None..0]
             Order.typeId.displayable => [None..0]
             Order.classCode => [None..0]
             Order.moodCode => [None..0]
             Order.id => [None..None]
             Order.id.nullFlavor => [None..0]
             Order.id.assigningAuthorityName => [None..0]
             Order.id.displayable => [None..0]
             Order.id.root => [1..None]
             Order.id.extension => [None..None]
             Order.code => [None..0]
             Order.priorityCode => [None..0]
        } 

        class FrParentDocument{

             ParentDocument => [None..None]
             ParentDocument.nullFlavor => [None..0]
             ParentDocument.id => [None..1]
             ParentDocument.id.assigningAuthorityName => [None..0]
             ParentDocument.id.displayable => [None..0]
             ParentDocument.id.root => [1..None]
             ParentDocument.id.extension => [None..None]
        } 

        class FrParticipant{

             Participant1 => [None..None]
             Participant1.typeId.nullFlavor => [None..0]
             Participant1.typeId.assigningAuthorityName => [None..0]
             Participant1.typeId.displayable => [None..0]
             Participant1.typeCode => [None..None]
             Participant1.contextControlCode => [None..0]
             Participant1.functionCode => [None..None]
             Participant1.functionCode.nullFlavor => [None..0]
             Participant1.functionCode.code => [1..None]
             Participant1.functionCode.codeSystem => [1..None]
             Participant1.functionCode.codeSystemVersion => [None..0]
             Participant1.functionCode.sdtcValueSet => [None..0]
             Participant1.functionCode.sdtcValueSetVersion => [None..0]
             Participant1.functionCode.originalText => [None..None]
             Participant1.time => [1..None]
             Participant1.time.operator => [None..0]
             Participant1.time.low => [None..None]
             Participant1.time.center => [None..0]
             Participant1.time.width => [None..0]
             Participant1.time.high => [None..None]
             Participant1.associatedEntity => [None..None]
             Participant1.associatedEntity.classCode => [None..None]
             Participant1.associatedEntity.id => [None..None]
             Participant1.associatedEntity.id.root => [None..None]
             Participant1.associatedEntity.id.extension => [None..None]
             Participant1.associatedEntity.code => [None..None]
             Participant1.associatedEntity.addr => [None..None]
             Participant1.associatedEntity.telecom => [None..None]
             Participant1.associatedEntity.associatedPerson => [None..None]
             Participant1.associatedEntity.scopingOrganization => [None..None]
        } 

        class FrPatientRole{

             PatientRole => [None..None]
             PatientRole.nullFlavor => [None..0]
             PatientRole.realmCode => [None..0]
             PatientRole.typeId => [None..0]
             PatientRole.templateId => [None..0]
             PatientRole.classCode => [None..0]
             PatientRole.sdtcIdentifiedBy => [None..0]
             PatientRole.patient => [1..None]
             PatientRole.providerOrganization => [None..0]
        } 

        class FrPatient{

             Patient.typeId.nullFlavor => [None..0]
             Patient.typeId.assigningAuthorityName => [None..0]
             Patient.typeId.displayable => [None..0]
             Patient.determinerCode => [None..0]
             Patient.name => [1..1]
             Patient.administrativeGenderCode => [1..None]
             Patient.birthTime => [1..None]
             Patient.maritalStatusCode => [None..0]
             Patient.religiousAffiliationCode => [None..0]
             Patient.raceCode => [None..0]
             Patient.sdtcRaceCode => [None..0]
             Patient.ethnicGroupCode => [None..0]
             Patient.sdtcEthnicGroupCode => [None..0]
             Patient.languageCommunication => [None..0]
        } 

        class FrPerformer{

             Performer1.typeId.nullFlavor => [None..0]
             Performer1.typeId.assigningAuthorityName => [None..0]
             Performer1.typeId.displayable => [None..0]
             Performer1.typeCode => [None..None]
             Performer1.functionCode => [None..None]
             Performer1.time => [None..None]
             Performer1.assignedEntity => [None..None]
             Performer1.assignedEntity.code => [None..None]
        } 

        class FrAssignedPerson{

             Person.nullFlavor => [None..0]
             Person.typeId.nullFlavor => [None..0]
             Person.typeId.assigningAuthorityName => [None..0]
             Person.typeId.displayable => [None..0]
             Person.classCode => [None..0]
             Person.determinerCode => [None..0]
             Person.name => [1..1]
             Person.name.family => [1..1]
             Person.name.given => [None..1]
             Person.name.prefix => [None..1]
             Person.name.suffix => [None..None]
             Person.name.validTime => [None..0]
             Person.name.nullFlavor => [None..0]
             Person.name.use => [None..0]
             Person.sdtcDesc => [None..0]
             Person.sdtcAsPatientRelationship => [None..0]
        } 

        class FrCorePractitioner{

             Practitioner => [None..None]
        } 

        class FrRecordTarget{

             RecordTarget => [None..None]
             RecordTarget.nullFlavor => [None..0]
             RecordTarget.typeId.nullFlavor => [None..0]
             RecordTarget.typeId.assigningAuthorityName => [None..0]
             RecordTarget.typeId.displayable => [None..0]
             RecordTarget.typeCode => [None..0]
             RecordTarget.contextControlCode => [None..0]
             RecordTarget.patientRole => [None..None]
        } 

        class FrRelatedDocument{

             RelatedDocument => [None..None]
             RelatedDocument.typeId.nullFlavor => [None..0]
             RelatedDocument.typeId.assigningAuthorityName => [None..0]
             RelatedDocument.typeId.displayable => [None..0]
             RelatedDocument.typeCode => [None..None]
             RelatedDocument.parentDocument => [None..None]
        } 

        class FrRelatedEntity{

             RelatedEntity.nullFlavor => [None..0]
             RelatedEntity.typeId.nullFlavor => [None..0]
             RelatedEntity.typeId.assigningAuthorityName => [None..0]
             RelatedEntity.typeId.displayable => [None..0]
             RelatedEntity.classCode => [None..None]
             RelatedEntity.code => [None..None]
             RelatedEntity.code.nullFlavor => [None..0]
             RelatedEntity.code.code => [1..None]
             RelatedEntity.code.codeSystem => [1..None]
             RelatedEntity.code.codeSystemVersion => [None..0]
             RelatedEntity.code.displayName => [1..None]
             RelatedEntity.code.sdtcValueSet => [None..0]
             RelatedEntity.code.sdtcValueSetVersion => [None..0]
             RelatedEntity.telecom => [1..None]
             RelatedEntity.relatedPerson => [1..None]
        } 

        class FrRepresentedCustodianOrganization{

             CustodianOrganization.typeId.nullFlavor => [None..0]
             CustodianOrganization.typeId.assigningAuthorityName => [None..0]
             CustodianOrganization.typeId.displayable => [None..0]
             CustodianOrganization.classCode => [None..0]
             CustodianOrganization.determinerCode => [None..0]
             CustodianOrganization.id => [None..1]
             CustodianOrganization.sdtcTelecom => [None..0]
        } 

        class FrRepresentedOrganization{

             Organization.typeId.nullFlavor => [None..0]
             Organization.typeId.assigningAuthorityName => [None..0]
             Organization.typeId.displayable => [None..0]
             Organization.classCode => [None..0]
             Organization.determinerCode => [None..0]
             Organization.name => [None..1]
             Organization.standardIndustryClassCode => [None..None]
        } 

        class FrServiceEvent{

             ServiceEvent => [None..None]
             ServiceEvent.nullFlavor => [None..0]
             ServiceEvent.typeId.nullFlavor => [None..0]
             ServiceEvent.typeId.assigningAuthorityName => [None..0]
             ServiceEvent.typeId.displayable => [None..0]
             ServiceEvent.classCode => [None..0]
             ServiceEvent.moodCode => [None..0]
             ServiceEvent.id => [None..None]
             ServiceEvent.code => [None..None]
             ServiceEvent.code.nullFlavor => [None..0]
             ServiceEvent.code.code => [1..None]
             ServiceEvent.code.codeSystem => [1..None]
             ServiceEvent.code.codeSystemVersion => [None..0]
             ServiceEvent.code.displayName => [1..None]
             ServiceEvent.code.sdtcValueSet => [None..0]
             ServiceEvent.code.sdtcValueSetVersion => [None..0]
             ServiceEvent.code.translation => [None..None]
             ServiceEvent.code.translation.nullFlavor => [None..0]
             ServiceEvent.code.translation.codeSystemVersion => [None..0]
             ServiceEvent.code.translation.sdtcValueSet => [None..0]
             ServiceEvent.code.translation.sdtcValueSetVersion => [None..0]
             ServiceEvent.code.translation.qualifier => [None..None]
             ServiceEvent.effectiveTime => [None..None]
             ServiceEvent.effectiveTime.nullFlavor => [None..0]
             ServiceEvent.effectiveTime.operator => [None..0]
             ServiceEvent.effectiveTime.low => [1..None]
             ServiceEvent.effectiveTime.center => [None..0]
             ServiceEvent.effectiveTime.width => [None..0]
             ServiceEvent.effectiveTime.high => [None..None]
             ServiceEvent.performer => [None..1]
             ServiceEvent.performer.typeCode => [None..None]
         }

     }
     package extension #paleturquoise {


        class AccessionNumberExtension{

          Extension.extension:accessionNumber => [0..1]
          Extension.extension:accessionNumber.url => [None..None]
          Extension.url => [None..None]
          Extension.value[x] => [None..0]
         }
     }
     package valueset #PaleVioletRed{
       }

package "Ressources de base" #palegreen {

 class "http://hl7.org/cda/stds/core/StructureDefinition/AssignedAuthor" as  class58510d48686a6398080b7be0a9488a07 

    class58510d48686a6398080b7be0a9488a07 --> FrAssignedAuthor

 class "http://hl7.org/cda/stds/core/StructureDefinition/AssignedCustodian" as  class9d6ae0bd4aff182e6679539d1b5e57dd 

    class9d6ae0bd4aff182e6679539d1b5e57dd --> FrAssignedCustodian

 class "http://hl7.org/cda/stds/core/StructureDefinition/AssignedEntity" as  classa57c2cf8eee922b736f24aae263fb85a 

    classa57c2cf8eee922b736f24aae263fb85a --> FrAssignedEntity

 class "http://hl7.org/cda/stds/core/StructureDefinition/AssociatedEntity" as  classf02f59ca36afce3537fd13cedd8610bc 

    classf02f59ca36afce3537fd13cedd8610bc --> FrAssociatedEntity

 class "http://hl7.org/cda/stds/core/StructureDefinition/Authenticator" as  class53108c7e3b2a59607cdb20ab0b268d03 

    class53108c7e3b2a59607cdb20ab0b268d03 --> FrAuthenticator

 class "http://hl7.org/cda/stds/core/StructureDefinition/Author" as  class937cfe84638a385773bc82a876cf4a8d 

    class937cfe84638a385773bc82a876cf4a8d --> FrAuthor

 class "http://hl7.org/cda/stds/core/StructureDefinition/AuthoringDevice" as  classf46502fb30744212b0c5841a6e4ea035 

    classf46502fb30744212b0c5841a6e4ea035 --> FrAuthoringDevice

 class "http://hl7.org/cda/stds/core/StructureDefinition/Authorization" as  class598114d4c6d4bf797def36d247d40839 

    class598114d4c6d4bf797def36d247d40839 --> FrAuthorization

 class "http://hl7.org/cda/stds/core/StructureDefinition/ComponentOf" as  class4277423a305ecb24dc9d37288c280772 

    class4277423a305ecb24dc9d37288c280772 --> FrComponentOf

 class "http://hl7.org/cda/stds/core/StructureDefinition/Custodian" as  classd84e4a39bf094111de7518d5a5411c66 

    classd84e4a39bf094111de7518d5a5411c66 --> FrCustodian

 class "http://hl7.org/cda/stds/core/StructureDefinition/DataEnterer" as  class637494ebd710a0dd928d3bba66f7c36c 

    class637494ebd710a0dd928d3bba66f7c36c --> FrDataEnterer

 class "http://hl7.org/cda/stds/core/StructureDefinition/DocumentationOf" as  class0977267ea48347e7fb26a0e81e862268 

    class0977267ea48347e7fb26a0e81e862268 --> FrDocumentationOf

 class "http://hl7.org/cda/stds/core/StructureDefinition/InFulfillmentOf" as  classe90f25fe105c3c9c4c47c62629a3765d 

    classe90f25fe105c3c9c4c47c62629a3765d --> FrInFulfillmentOf

 class "http://hl7.org/cda/stds/core/StructureDefinition/Informant" as  class0bdf5ad046cc54eb3cb2ac8f5bc2f2c8 

    class0bdf5ad046cc54eb3cb2ac8f5bc2f2c8 --> FrInformant

 class "http://hl7.org/cda/stds/core/StructureDefinition/InformationRecipient" as  classb6fd1ae4a9b50563c83e48eaaf673af4 

    classb6fd1ae4a9b50563c83e48eaaf673af4 --> FrInformationRecipient

 class "http://hl7.org/cda/stds/core/StructureDefinition/IntendedRecipient" as  classb4c0abb01d11eefbc617aa004a0b6393 

    classb4c0abb01d11eefbc617aa004a0b6393 --> FrIntendedRecipient

 class "http://hl7.org/cda/stds/core/StructureDefinition/LegalAuthenticator" as  class57f35676579cccc1659c4601fa19b43b 

    class57f35676579cccc1659c4601fa19b43b --> FrLegalAuthenticator

 class "http://hl7.org/cda/stds/core/StructureDefinition/Order" as  class358c910e07ad3f95a61b1dae6d4a35be 

    class358c910e07ad3f95a61b1dae6d4a35be --> FrOrder

 class "http://hl7.org/cda/stds/core/StructureDefinition/ParentDocument" as  class4313f3b50ac00c5473aecb642b99f6e4 

    class4313f3b50ac00c5473aecb642b99f6e4 --> FrParentDocument

 class "http://hl7.org/cda/stds/core/StructureDefinition/Participant1" as  class2fd9a3b182710aa68f9e615904fe1537 

    class2fd9a3b182710aa68f9e615904fe1537 --> FrParticipant

 class "http://hl7.org/cda/stds/core/StructureDefinition/PatientRole" as  class1e213e8519f12110736b032cda341174 

    class1e213e8519f12110736b032cda341174 --> FrPatientRole

 class "http://hl7.org/cda/stds/core/StructureDefinition/Patient" as  classa8889bb6f3999fb5243b3ed3b492e0c4 

    classa8889bb6f3999fb5243b3ed3b492e0c4 --> FrPatient

 class "http://hl7.org/cda/stds/core/StructureDefinition/Performer1" as  class2322ea8c73e0b95c4de59f56ee36a694 

    class2322ea8c73e0b95c4de59f56ee36a694 --> FrPerformer

 class "http://hl7.org/cda/stds/core/StructureDefinition/Person" as  classb14b9f756425869ebeb8ade0004931e1 

    classb14b9f756425869ebeb8ade0004931e1 --> FrAssignedPerson

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-practitioner" as  class722d091912544e694771fe1d2c6739cb 

    class722d091912544e694771fe1d2c6739cb --> FrCorePractitioner

 class "http://hl7.org/cda/stds/core/StructureDefinition/RecordTarget" as  class0baedfe5573df35f7a6ee5934c45b818 

    class0baedfe5573df35f7a6ee5934c45b818 --> FrRecordTarget

 class "http://hl7.org/cda/stds/core/StructureDefinition/RelatedDocument" as  classddc7c43262268f3e7ef73c1c5ad6b514 

    classddc7c43262268f3e7ef73c1c5ad6b514 --> FrRelatedDocument

 class "http://hl7.org/cda/stds/core/StructureDefinition/RelatedEntity" as  class0a3bfa693dae125e5c0a4e8cab321d9a 

    class0a3bfa693dae125e5c0a4e8cab321d9a --> FrRelatedEntity

 class "http://hl7.org/cda/stds/core/StructureDefinition/CustodianOrganization" as  class958e4615d47e79ed7eef2368401c733a 

    class958e4615d47e79ed7eef2368401c733a --> FrRepresentedCustodianOrganization

 class "http://hl7.org/cda/stds/core/StructureDefinition/Organization" as  class70defb4802516f8b110654a1e3649ed7 

    class70defb4802516f8b110654a1e3649ed7 --> FrRepresentedOrganization

 class "http://hl7.org/cda/stds/core/StructureDefinition/ServiceEvent" as  class21fc45b6eacaebf264ceab7c3130a980 

    class21fc45b6eacaebf264ceab7c3130a980 --> FrServiceEvent
}
@enduml