@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class AssociationPrescription{

             AssociationPrescription => [None..None]
             AssociationPrescription.prescription => [1..1]
             AssociationPrescription.prescription.identifiant => [0..1]
             AssociationPrescription.accessionNumber => [0..1]
        } 

        class AssociationPriseEncharge{

             AssociationPriseEncharge => [None..None]
             AssociationPriseEncharge.priseEnCharge => [1..1]
             AssociationPriseEncharge.priseEnCharge.identifiantPriseEnCharge => [0..*]
             AssociationPriseEncharge.priseEnCharge.typePriseEnCharge => [0..1]
             AssociationPriseEncharge.priseEnCharge.dateDebutFinPriseEnCharge => [1..1]
             AssociationPriseEncharge.priseEnCharge.typeSortie => [0..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge => [0..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge => [1..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.identifiantPS => [1..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.professionSavoirfaireRole => [0..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.adresse => [0..*]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.coordonneesTelecom => [0..*]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.personnePhysique => [0..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.personnePhysique.nomPersonne => [1..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.personnePhysique.nomPersonne.nom => [1..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.personnePhysique.nomPersonne.prenom => [0..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.personnePhysique.nomPersonne.civilite => [0..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.personnePhysique.nomPersonne.titre => [0..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.structurePS => [0..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.structurePS.identifiantStructure => [0..*]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.structurePS.nomStructure => [0..1]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.structurePS.coordonneesTelecomStructure => [0..*]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.structurePS.adresseStructure => [0..*]
             AssociationPriseEncharge.priseEnCharge.responsablePriseEnCharge.entiteResponsablePriseEnCharge.structurePS.cadreExercice => [0..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge => [0..*]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.typeParticipation => [1..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.dateDebutFinParticipation => [0..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique => [1..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.identifiant => [1..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.professionSavoirfaireRole => [0..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.adresse => [0..*]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.coordonneesTelecom => [0..*]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.personnePhysique => [0..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.personnePhysique.nomPersonne => [1..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.personnePhysique.nomPersonne.nom => [1..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.personnePhysique.nomPersonne.prenom => [0..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.personnePhysique.nomPersonne.civilite => [0..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.personnePhysique.nomPersonne.titre => [0..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.structurePS => [0..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.structurePS.identifiantStructure => [0..*]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.structurePS.nomStructure => [0..1]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.structurePS.coordonneesTelecomStructure => [0..*]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.structurePS.adresseStructure => [0..*]
             AssociationPriseEncharge.priseEnCharge.personneImpliqueePriseEnCharge.professionnelImplique.structurePS.cadreExercice => [0..1]
             AssociationPriseEncharge.priseEnCharge.lieuPriseEnCharge => [1..1]
             AssociationPriseEncharge.priseEnCharge.lieuPriseEnCharge.structurePriseEnChargee => [1..1]
             AssociationPriseEncharge.priseEnCharge.lieuPriseEnCharge.structurePriseEnChargee.secteurActivite => [1..1]
             AssociationPriseEncharge.priseEnCharge.lieuPriseEnCharge.structurePriseEnChargee.secteurActivite.categorieEtablissement => [0..1]
             AssociationPriseEncharge.priseEnCharge.lieuPriseEnCharge.structurePriseEnChargee.localisationStructure => [1..1]
             AssociationPriseEncharge.priseEnCharge.lieuPriseEnCharge.structurePriseEnChargee.localisationStructure.nomStructure => [0..1]
             AssociationPriseEncharge.priseEnCharge.lieuPriseEnCharge.structurePriseEnChargee.localisationStructure.adresseStructure => [0..1]
        } 

        class AuteurDocument{

             AuteurDocument => [None..None]
             AuteurDocument.horodatageParticipation => [1..1]
             AuteurDocument.roleFonctionnel => [0..1]
             AuteurDocument.precisionRoleFonctionnel => [0..1]
             AuteurDocument.auteur[x] => [0..1]
        } 

        class ConsentementDocument{

             ConsentementDocument => [None..None]
             ConsentementDocument.consentement => [1..1]
             ConsentementDocument.consentement.identifiantConsentement => [0..*]
             ConsentementDocument.consentement.typeConsentement => [1..1]
             ConsentementDocument.consentement.statutConsentement => [1..1]
        } 

        class DestinatairePrevuDocument{

             DestinatairePrevuDocument => [None..None]
             DestinatairePrevuDocument.identifiantDestinataire => [0..*]
             DestinatairePrevuDocument.adresseDestinataire => [0..*]
             DestinatairePrevuDocument.coordonneesTelecomDestinataire => [0..*]
             DestinatairePrevuDocument.informationsSurDestintaire => [0..1]
             DestinatairePrevuDocument.informationsSurDestintaire.nomDestinataire => [0..*]
             DestinatairePrevuDocument.informationsSurDestintaire.nomDestinataire.nom => [1..1]
             DestinatairePrevuDocument.informationsSurDestintaire.nomDestinataire.prenom => [0..1]
             DestinatairePrevuDocument.informationsSurDestintaire.nomDestinataire.civilite => [0..1]
             DestinatairePrevuDocument.informationsSurDestintaire.nomDestinataire.titre => [0..1]
             DestinatairePrevuDocument.structureDestinataire => [0..1]
             DestinatairePrevuDocument.structureDestinataire.identifiantStructure => [0..1]
             DestinatairePrevuDocument.structureDestinataire.nomStructure => [0..*]
             DestinatairePrevuDocument.structureDestinataire.coordonneesTelecomStructure => [0..*]
             DestinatairePrevuDocument.structureDestinataire.adresseStructure => [0..1]
        } 

        class DocumentReference{

             DocumentReference => [None..None]
             DocumentReference.typeReference => [1..1]
             DocumentReference.parentDocument => [1..1]
             DocumentReference.parentDocument.identifiantUniqueDocument => [1..1]
        } 

        class EnteteDocument{

             EnteteDocument => [None..None]
             EnteteDocument.identifiantUniqueDocument => [1..1]
             EnteteDocument.modeleDocument => [1..1]
             EnteteDocument.typeDocument => [1..1]
             EnteteDocument.titreDocument => [1..1]
             EnteteDocument.dateDeCreation => [1..1]
             EnteteDocument.niveauConfidentialite => [1..1]
             EnteteDocument.languePrincipaleDocument => [1..1]
             EnteteDocument.identifiantDuLotDeVersions => [1..1]
             EnteteDocument.versionDocument => [1..1]
             EnteteDocument.statutDocument => [1..1]
             EnteteDocument.patientDocument => [1..1]
             EnteteDocument.auteurDocument => [1..*]
             EnteteDocument.informateurDocument => [0..*]
             EnteteDocument.structureConservationDocument => [1..1]
             EnteteDocument.destinataireDocument => [0..*]
             EnteteDocument.responsableDocuement => [1..1]
             EnteteDocument.validateurDocument => [0..*]
             EnteteDocument.operateurSaisie => [0..1]
             EnteteDocument.participant => [0..*]
             EnteteDocument.associationPrescription => [1..1]
             EnteteDocument.evenementDocumente => [1..*]
             EnteteDocument.documentReference => [0..1]
             EnteteDocument.consentementAssocieAuDocument => [0..*]
             EnteteDocument.associationPriseEncharge => [1..1]
        } 

        class EvenementDocumente{

             EvenementDocumente => [None..None]
             EvenementDocumente.evenementDocumente => [1..1]
             EvenementDocumente.evenementDocumente.identifiantSpecifique => [0..*]
             EvenementDocumente.evenementDocumente.statut => [0..*]
             EvenementDocumente.evenementDocumente.codeEvenement => [0..1]
             EvenementDocumente.evenementDocumente.codeEvenement.translation => [0..*]
             EvenementDocumente.evenementDocumente.dateHeureEvenement => [0..1]
             EvenementDocumente.evenementDocumente.executantEvenement => [1..1]
             EvenementDocumente.evenementDocumente.executantEvenement.roleFonctionnel => [0..1]
             EvenementDocumente.evenementDocumente.executantEvenement.dateHeureParticipation => [0..1]
             EvenementDocumente.evenementDocumente.executantEvenement.executant => [1..1]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.identifiant => [1..1]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.professionSavoirfaireRole => [0..1]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.adresse => [0..*]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.coordonneesTelecom => [0..*]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.personnePhysique => [0..1]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.personnePhysique.nomPersonne => [1..1]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.personnePhysique.nomPersonne.nom => [1..1]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.personnePhysique.nomPersonne.prenom => [0..1]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.personnePhysique.nomPersonne.civilite => [0..1]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.personnePhysique.nomPersonne.titre => [0..1]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.structureResponsable => [0..1]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.structureResponsable.identifiantStructure => [0..*]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.structureResponsable.nomStructure => [0..1]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.structureResponsable.coordonneesTelecomStructure => [0..*]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.structureResponsable.adresseStructure => [0..*]
             EvenementDocumente.evenementDocumente.executantEvenement.executant.structureResponsable.cadreExercice => [1..1]
        } 

        class InformateurDocument{

             InformateurDocument => [None..None]
             InformateurDocument.informateur[x] => [1..1]
        } 

        class NonProfessionnelDocument{

             NonProfessionnelDocument => [None..None]
             NonProfessionnelDocument.rolePersonne => [1..1]
             NonProfessionnelDocument.lienPatient => [0..1]
             NonProfessionnelDocument.lienPatient.precisionLien => [0..*]
             NonProfessionnelDocument.adressePersonne => [0..*]
             NonProfessionnelDocument.coordonneesTelecom => [0..*]
             NonProfessionnelDocument.personnePhysique => [1..1]
             NonProfessionnelDocument.personnePhysique.nomPersonne => [1..1]
             NonProfessionnelDocument.personnePhysique.nomPersonne.nom => [1..1]
             NonProfessionnelDocument.personnePhysique.nomPersonne.prenom => [0..1]
        } 

        class OperateurSaisie{

             OperateurSaisie => [None..None]
             OperateurSaisie.dateSaisie => [1..1]
             OperateurSaisie.operateurSaisie => [1..1]
             OperateurSaisie.operateurSaisie.identifiant => [1..1]
             OperateurSaisie.operateurSaisie.professionSavoirfaireRole => [0..1]
             OperateurSaisie.operateurSaisie.adresse => [0..*]
             OperateurSaisie.operateurSaisie.coordonneesTelecom => [0..*]
             OperateurSaisie.operateurSaisie.personnePhysique => [0..1]
             OperateurSaisie.operateurSaisie.personnePhysique.nomPersonne => [1..1]
             OperateurSaisie.operateurSaisie.personnePhysique.nomPersonne.nom => [1..1]
             OperateurSaisie.operateurSaisie.personnePhysique.nomPersonne.prenom => [0..1]
             OperateurSaisie.operateurSaisie.personnePhysique.nomPersonne.civilite => [0..1]
             OperateurSaisie.operateurSaisie.personnePhysique.nomPersonne.titre => [0..1]
             OperateurSaisie.operateurSaisie.structure => [0..1]
             OperateurSaisie.operateurSaisie.structure.identifiant => [0..*]
             OperateurSaisie.operateurSaisie.structure.nom => [0..1]
             OperateurSaisie.operateurSaisie.structure.coordonneesTelecom => [0..*]
             OperateurSaisie.operateurSaisie.structure.adresse => [0..*]
             OperateurSaisie.operateurSaisie.structure.cadreExercice => [0..1]
        } 

        class ParticipantDocument{

             ParticipantDocument => [None..None]
             ParticipantDocument.typeParticipation => [1..1]
             ParticipantDocument.roleFonctionnel => [0..1]
             ParticipantDocument.roleFonctionnel.precision => [0..1]
             ParticipantDocument.dateDebutEtOuFinParticipation => [1..1]
             ParticipantDocument.identificationParticipant => [1..1]
             ParticipantDocument.identificationParticipant.ProfessionnelNonProfessionnel => [1..1]
             ParticipantDocument.identificationParticipant.identifiantParticipant => [1..1]
             ParticipantDocument.identificationParticipant.professionSavoirfaireRole => [0..1]
             ParticipantDocument.identificationParticipant.adresse => [0..*]
             ParticipantDocument.identificationParticipant.coordonneesTelecomStructure => [0..*]
             ParticipantDocument.identificationParticipant.personnePhysique => [0..1]
             ParticipantDocument.identificationParticipant.personnePhysique.nomPersonne => [1..1]
             ParticipantDocument.identificationParticipant.personnePhysique.nomPersonne.nom => [1..1]
             ParticipantDocument.identificationParticipant.personnePhysique.nomPersonne.prenom => [0..1]
             ParticipantDocument.identificationParticipant.personnePhysique.nomPersonne.civilite => [0..1]
             ParticipantDocument.identificationParticipant.personnePhysique.nomPersonne.titre => [0..1]
             ParticipantDocument.identificationParticipant.structureResponsable => [0..1]
             ParticipantDocument.identificationParticipant.structureResponsable.identifiantStructure => [0..*]
             ParticipantDocument.identificationParticipant.structureResponsable.nomStructure => [0..1]
             ParticipantDocument.identificationParticipant.structureResponsable.coordonneesTelecomStructure => [0..*]
             ParticipantDocument.identificationParticipant.structureResponsable.adresseStructure => [0..*]
        } 

        class PatientDocument{

             PatientDocument => [None..None]
             PatientDocument.identifiantPatient => [1..1]
             PatientDocument.adresse => [0..*]
             PatientDocument.coordonneesTelecom => [0..*]
             PatientDocument.personnePhysique => [0..1]
             PatientDocument.personnePhysique.nomsPrenom => [0..1]
             PatientDocument.personnePhysique.nomsPrenom.noms => [0..1]
             PatientDocument.personnePhysique.nomsPrenom.noms.nomNaissance => [0..1]
             PatientDocument.personnePhysique.nomsPrenom.noms.nomUtilise => [0..1]
             PatientDocument.personnePhysique.nomsPrenom.prenom => [0..1]
             PatientDocument.personnePhysique.nomsPrenom.prenom.listePrenoms => [0..1]
             PatientDocument.personnePhysique.nomsPrenom.prenom.premierPrenom => [0..1]
             PatientDocument.personnePhysique.nomsPrenom.prenom.premierNomUtilise => [0..1]
             PatientDocument.personnePhysique.sexe => [1..1]
             PatientDocument.personnePhysique.dateNaissance => [1..1]
             PatientDocument.personnePhysique.dateDeces => [0..1]
             PatientDocument.personnePhysique.grossesseMultiple => [0..1]
             PatientDocument.personnePhysique.numeroOrdreNaissance => [0..1]
             PatientDocument.personnePhysique.representantPatient => [0..*]
             PatientDocument.personnePhysique.representantPatient.adresse => [0..*]
             PatientDocument.personnePhysique.representantPatient.coordonneesTelecom => [0..*]
             PatientDocument.personnePhysique.representantPatient.personneRepresentantPatient => [0..1]
             PatientDocument.personnePhysique.representantPatient.personneRepresentantPatient.nomPrenom => [0..1]
             PatientDocument.personnePhysique.representantPatient.personneRepresentantPatient.nomPrenom.nom => [0..1]
             PatientDocument.personnePhysique.representantPatient.personneRepresentantPatient.nomPrenom.prenom => [0..*]
             PatientDocument.personnePhysique.representantPatient.personneRepresentantPatient.structureRepresentatntPatient => [0..1]
             PatientDocument.personnePhysique.representantPatient.personneRepresentantPatient.structureRepresentatntPatient.identifiant => [0..1]
             PatientDocument.personnePhysique.representantPatient.personneRepresentantPatient.structureRepresentatntPatient.nom => [0..1]
             PatientDocument.personnePhysique.representantPatient.personneRepresentantPatient.structureRepresentatntPatient.lieuNaissance => [0..1]
             PatientDocument.personnePhysique.representantPatient.personneRepresentantPatient.structureRepresentatntPatient.lieuNaissance.lieu => [1..1]
             PatientDocument.personnePhysique.representantPatient.personneRepresentantPatient.structureRepresentatntPatient.lieuNaissance.lieu.nomLieuNaissance => [0..1]
             PatientDocument.personnePhysique.representantPatient.personneRepresentantPatient.structureRepresentatntPatient.lieuNaissance.lieu.adresseEtCodeOfficielGeographique => [0..1]
             PatientDocument.personnePhysique.representantPatient.personneRepresentantPatient.structureRepresentatntPatient.lieuNaissance.lieu.adresseEtCodeOfficielGeographique.CodeOfficielGeographique => [0..1]
        } 

        class ProfessionnelAuteurDocument{

             ProfessionnelAuteurDocument => [None..None]
             ProfessionnelAuteurDocument.identificationAuteur => [1..*]
             ProfessionnelAuteurDocument.identificationAuteur.identifiant => [0..*]
             ProfessionnelAuteurDocument.identificationAuteur.professionSavoirFaireRole => [0..1]
             ProfessionnelAuteurDocument.identificationAuteur.adresse => [0..*]
             ProfessionnelAuteurDocument.identificationAuteur.coordonneesTelecom => [0..*]
             ProfessionnelAuteurDocument.identificationAuteur.identiteAuteur => [1..1]
             ProfessionnelAuteurDocument.identificationAuteur.identiteAuteur.nomAuteur => [1..1]
             ProfessionnelAuteurDocument.identificationAuteur.identiteAuteur.nomAuteur.nom => [1..1]
             ProfessionnelAuteurDocument.identificationAuteur.identiteAuteur.nomAuteur.prenom => [0..1]
             ProfessionnelAuteurDocument.identificationAuteur.identiteAuteur.nomAuteur.civilite => [0..1]
             ProfessionnelAuteurDocument.identificationAuteur.identiteAuteur.nomAuteur.titre => [0..1]
             ProfessionnelAuteurDocument.identificationAuteur.structure => [1..1]
             ProfessionnelAuteurDocument.identificationAuteur.structure.identifiantStructure => [0..1]
             ProfessionnelAuteurDocument.identificationAuteur.structure.nomStructure => [0..1]
        } 

        class ProfessionnelDocument{

             ProfessionnelDocument => [None..None]
             ProfessionnelDocument.identifiant => [1..1]
             ProfessionnelDocument.professionSavoirFaireRole => [0..1]
             ProfessionnelDocument.adresse => [0..*]
             ProfessionnelDocument.coordonneesTelecom => [0..*]
             ProfessionnelDocument.personnePhysique => [0..1]
             ProfessionnelDocument.personnePhysique.identitePersonne => [1..1]
             ProfessionnelDocument.personnePhysique.identitePersonne.nomPersonne => [1..1]
             ProfessionnelDocument.personnePhysique.identitePersonne.prenomPersonne => [0..1]
             ProfessionnelDocument.personnePhysique.identitePersonne.civilite => [0..1]
             ProfessionnelDocument.personnePhysique.identitePersonne.titre => [0..1]
             ProfessionnelDocument.structure => [0..1]
             ProfessionnelDocument.structure.identifiantStructure => [0..*]
             ProfessionnelDocument.structure.nomStructure => [0..1]
             ProfessionnelDocument.structure.coordonneesTelecomStructure => [0..*]
             ProfessionnelDocument.structure.adresseStructure => [0..*]
             ProfessionnelDocument.structure.cadreExercice => [0..1]
        } 

        class ResponsableDocument{

             ResponsableDocument => [None..None]
             ResponsableDocument.dateHeureAttestationValidite => [1..1]
             ResponsableDocument.ProfessionnelResponsableDocument => [1..1]
             ResponsableDocument.ProfessionnelResponsableDocument.identifiant => [1..1]
             ResponsableDocument.ProfessionnelResponsableDocument.professionSavoirfaireRole => [0..1]
             ResponsableDocument.ProfessionnelResponsableDocument.adresse => [0..*]
             ResponsableDocument.ProfessionnelResponsableDocument.coordonneesTelecomStructure => [0..*]
             ResponsableDocument.ProfessionnelResponsableDocument.personnePhysique => [0..1]
             ResponsableDocument.ProfessionnelResponsableDocument.personnePhysique.nomPersonne => [1..1]
             ResponsableDocument.ProfessionnelResponsableDocument.personnePhysique.nomPersonne.nom => [1..1]
             ResponsableDocument.ProfessionnelResponsableDocument.personnePhysique.nomPersonne.prenom => [0..1]
             ResponsableDocument.ProfessionnelResponsableDocument.personnePhysique.nomPersonne.civilite => [0..1]
             ResponsableDocument.ProfessionnelResponsableDocument.personnePhysique.nomPersonne.titre => [0..1]
             ResponsableDocument.ProfessionnelResponsableDocument.structureResponsable => [0..1]
             ResponsableDocument.ProfessionnelResponsableDocument.structureResponsable.identifiantStructure => [0..*]
             ResponsableDocument.ProfessionnelResponsableDocument.structureResponsable.nomStructure => [0..1]
             ResponsableDocument.ProfessionnelResponsableDocument.structureResponsable.coordonneesTelecomStructure => [0..*]
             ResponsableDocument.ProfessionnelResponsableDocument.structureResponsable.adresseStructure => [0..*]
             ResponsableDocument.ProfessionnelResponsableDocument.structureResponsable.cadreExercice => [0..1]
        } 

        class StructureConservationDocument{

             StructureConservationDocument => [None..None]
             StructureConservationDocument.identifiantStructure => [1..1]
             StructureConservationDocument.nomStructure => [0..1]
             StructureConservationDocument.coordonneesTelecomStructure => [0..1]
             StructureConservationDocument.adresseStructure => [0..1]
        } 

        class SystemeDocument{

             SystemeDocument => [None..None]
             SystemeDocument.identificationAuteur => [1..1]
             SystemeDocument.identificationAuteur.identifiantAuteur => [1..*]
             SystemeDocument.identificationAuteur.professionSavoirFaireRole => [0..1]
             SystemeDocument.identificationAuteur.systeme => [1..1]
             SystemeDocument.identificationAuteur.systeme.nomModeleSysteme => [1..1]
             SystemeDocument.identificationAuteur.systeme.nomSysteme => [1..1]
             SystemeDocument.identificationAuteur.structure => [1..1]
             SystemeDocument.identificationAuteur.structure.identifiantStructure => [0..1]
             SystemeDocument.identificationAuteur.structure.nomStructure => [0..1]
        } 

        class ValidateurDocument{

             ValidateurDocument => [None..None]
             ValidateurDocument.dateHeureAttestationValidite => [1..1]
             ValidateurDocument.ProfessionnelValidateurDocument => [1..1]
             ValidateurDocument.ProfessionnelValidateurDocument.identifiant => [1..1]
             ValidateurDocument.ProfessionnelValidateurDocument.professionSavoirfaireRole => [0..1]
             ValidateurDocument.ProfessionnelValidateurDocument.adresse => [0..*]
             ValidateurDocument.ProfessionnelValidateurDocument.coordonneesTelecomStructure => [0..*]
             ValidateurDocument.ProfessionnelValidateurDocument.personnePhysique => [0..1]
             ValidateurDocument.ProfessionnelValidateurDocument.personnePhysique.nomPersonne => [1..1]
             ValidateurDocument.ProfessionnelValidateurDocument.personnePhysique.nomPersonne.nom => [1..1]
             ValidateurDocument.ProfessionnelValidateurDocument.personnePhysique.nomPersonne.prenom => [0..1]
             ValidateurDocument.ProfessionnelValidateurDocument.personnePhysique.nomPersonne.civilite => [0..1]
             ValidateurDocument.ProfessionnelValidateurDocument.personnePhysique.nomPersonne.titre => [0..1]
             ValidateurDocument.ProfessionnelValidateurDocument.structurePS => [0..1]
             ValidateurDocument.ProfessionnelValidateurDocument.structurePS.identifiantStructure => [0..*]
             ValidateurDocument.ProfessionnelValidateurDocument.structurePS.nomStructure => [0..1]
             ValidateurDocument.ProfessionnelValidateurDocument.structurePS.coordonneesTelecomStructure => [0..*]
             ValidateurDocument.ProfessionnelValidateurDocument.structurePS.adresseStructure => [0..*]
             ValidateurDocument.ProfessionnelValidateurDocument.structurePS.cadreExercice => [0..1]
        } 

        class FrCompositionDocument{

             Composition => [None..None]
             Composition.meta.profile => [1..None]
             Composition.meta.profile:canonical => [1..1]
             Composition.extension => [1..None]
             Composition.extension:data-enterer => <&plus>[1..1]
             Composition.identifier => [1..None]
             Composition.status => [None..None]
             Composition.type => [None..None]
             Composition.subject => [1..None]
             Composition.subject.reference => [1..None]
             Composition.date => [None..None]
             Composition.author => [None..None]
             Composition.author.extension => [1..None]
             Composition.author.extension:time => <&plus>[1..1]
             Composition.title => [None..None]
             Composition.confidentiality => [1..None]
             Composition.attester => [2..None]
             Composition.attester:legal => [1..1]
             Composition.attester:legal.mode => [None..None]
             Composition.attester:legal.time => [1..None]
             Composition.attester:legal.party => [1..None]
             Composition.attester:professional => [1..1]
             Composition.attester:professional.mode => [None..None]
             Composition.attester:professional.time => [1..None]
             Composition.attester:professional.party => [None..None]
             Composition.custodian => [None..None]
             Composition.relatesTo.target[x] => [None..None]
             Composition.section => [1..None]
        } 

        class FrOrganizationDocument{

             Organization.implicitRules => [None..0]
             Organization.identifier => [None..None]
             Organization.active => [None..0]
             Organization.type => [None..1]
             Organization.name => [None..None]
        } 

        class FrBundleDocument{

             Bundle.identifier => [1..None]
             Bundle.type => [None..None]
             Bundle.timestamp => [1..None]
             Bundle.entry => [5..None]
             Bundle.entry.fullUrl => [1..None]
             Bundle.entry.search => [None..0]
             Bundle.entry.request => [None..0]
             Bundle.entry.response => [None..0]
             Bundle.entry:composition => [1..1]
             Bundle.entry:composition.resource => [None..None]
             Bundle.entry:patient => [0..1]
             Bundle.entry:patient.resource => [None..None]
             Bundle.entry:practitionerRole => [1..*]
             Bundle.entry:practitionerRole.resource => [None..None]
             Bundle.entry:practitioner => [1..*]
             Bundle.entry:practitioner.resource => [None..None]
             Bundle.entry:organization => [1..*]
             Bundle.entry:organization.resource => [None..None]
             Bundle.entry:device => [1..*]
             Bundle.entry:device.resource => [None..None]
        } 

        class FrAssignedAuthor{

             AssignedAuthor => [None..None]
             AssignedAuthor.nullFlavor => [None..0]
             AssignedAuthor.typeId.nullFlavor => [None..0]
             AssignedAuthor.typeId.assigningAuthorityName => [None..0]
             AssignedAuthor.typeId.displayable => [None..0]
             AssignedAuthor.classCode => [None..0]
             AssignedAuthor.id => [None..None]
             AssignedAuthor.id.nullFlavor => [None..0]
             AssignedAuthor.id.assigningAuthorityName => [None..0]
             AssignedAuthor.id.displayable => [None..0]
             AssignedAuthor.id.root => [1..None]
             AssignedAuthor.id.extension => [1..None]
             AssignedAuthor.sdtcIdentifiedBy => [None..0]
             AssignedAuthor.code => [None..None]
             AssignedAuthor.addr => [None..None]
             AssignedAuthor.telecom => [None..None]
             AssignedAuthor.assignedPerson => [None..None]
             AssignedAuthor.assignedAuthoringDevice => [None..None]
             AssignedAuthor.representedOrganization => [None..None]
        } 

        class FrAssignedCustodian{

             AssignedCustodian => [None..None]
             AssignedCustodian.typeId.nullFlavor => [None..0]
             AssignedCustodian.typeId.assigningAuthorityName => [None..0]
             AssignedCustodian.typeId.displayable => [None..0]
             AssignedCustodian.classCode => [None..0]
             AssignedCustodian.representedCustodianOrganization => [None..None]
        } 

        class FrAssignedEntity{

             AssignedEntity => [None..None]
             AssignedEntity.nullFlavor => [None..0]
             AssignedEntity.typeId.nullFlavor => [None..0]
             AssignedEntity.typeId.assigningAuthorityName => [None..0]
             AssignedEntity.typeId.displayable => [None..0]
             AssignedEntity.classCode => [None..0]
             AssignedEntity.id => [None..1]
             AssignedEntity.id.nullFlavor => [None..0]
             AssignedEntity.id.assigningAuthorityName => [None..0]
             AssignedEntity.id.displayable => [None..0]
             AssignedEntity.id.root => [1..None]
             AssignedEntity.id.extension => [1..None]
             AssignedEntity.sdtcIdentifiedBy => [None..0]
             AssignedEntity.code => [None..None]
             AssignedEntity.code.nullFlavor => [None..0]
             AssignedEntity.code.codeSystemVersion => [None..0]
             AssignedEntity.code.sdtcValueSet => [None..0]
             AssignedEntity.code.sdtcValueSetVersion => [None..0]
             AssignedEntity.addr => [None..None]
             AssignedEntity.telecom => [None..None]
             AssignedEntity.assignedPerson => [None..None]
             AssignedEntity.representedOrganization => [None..None]
             AssignedEntity.sdtcPatient => [None..0]
        } 

        class FrAssociatedEntity{

             AssociatedEntity => [None..None]
             AssociatedEntity.nullFlavor => [None..0]
             AssociatedEntity.typeId.nullFlavor => [None..0]
             AssociatedEntity.typeId.assigningAuthorityName => [None..0]
             AssociatedEntity.typeId.displayable => [None..0]
             AssociatedEntity.classCode => [None..None]
             AssociatedEntity.id => [None..None]
             AssociatedEntity.id.root => [None..None]
             AssociatedEntity.id.extension => [None..None]
             AssociatedEntity.sdtcIdentifiedBy => [None..0]
             AssociatedEntity.code => [None..None]
             AssociatedEntity.addr => [None..None]
             AssociatedEntity.telecom => [None..None]
             AssociatedEntity.associatedPerson => [None..None]
             AssociatedEntity.scopingOrganization => [None..None]
        } 

        class FrAuthenticator{

             Authenticator => [None..None]
             Authenticator.nullFlavor => [None..0]
             Authenticator.typeId.nullFlavor => [None..0]
             Authenticator.typeId.assigningAuthorityName => [None..0]
             Authenticator.typeId.displayable => [None..0]
             Authenticator.typeCode => [None..0]
             Authenticator.time => [None..None]
             Authenticator.time.value => [None..None]
             Authenticator.signatureCode => [None..None]
             Authenticator.signatureCode.sdtcValueSet => [None..0]
             Authenticator.signatureCode.sdtcValueSetVersion => [None..0]
             Authenticator.sdtcSignatureText => [None..0]
             Authenticator.assignedEntity => [None..None]
        } 

        class FrAuthor{

             Author => [None..None]
             Author.nullFlavor => [None..0]
             Author.typeId.nullFlavor => [None..0]
             Author.typeId.assigningAuthorityName => [None..0]
             Author.typeId.displayable => [None..0]
             Author.typeCode => [None..0]
             Author.contextControlCode => [None..0]
             Author.functionCode => [None..None]
             Author.functionCode.nullFlavor => [None..0]
             Author.functionCode.code => [1..None]
             Author.functionCode.codeSystem => [1..None]
             Author.functionCode.codeSystemVersion => [None..0]
             Author.functionCode.sdtcValueSet => [None..0]
             Author.functionCode.sdtcValueSetVersion => [None..0]
             Author.functionCode.originalText => [None..None]
             Author.time => [None..None]
             Author.time.value => [1..None]
             Author.assignedAuthor => [None..None]
        } 

        class FrAuthoringDevice{

             AuthoringDevice.typeId.nullFlavor => [None..0]
             AuthoringDevice.typeId.assigningAuthorityName => [None..0]
             AuthoringDevice.typeId.displayable => [None..0]
             AuthoringDevice.classCode => [None..0]
             AuthoringDevice.determinerCode => [None..0]
             AuthoringDevice.manufacturerModelName => [1..None]
             AuthoringDevice.softwareName => [1..None]
        } 

        class FrAuthorization{

             Authorization => [None..None]
             Authorization.typeId.nullFlavor => [None..0]
             Authorization.typeId.assigningAuthorityName => [None..0]
             Authorization.typeId.displayable => [None..0]
             Authorization.typeCode => [None..0]
             Authorization.consent => [None..None]
             Authorization.consent.id => [None..None]
             Authorization.consent.code => [1..None]
             Authorization.consent.statusCode.code => [None..None]
             Authorization.consent.statusCode.sdtcValueSet => [None..0]
             Authorization.consent.statusCode.sdtcValueSetVersion => [None..0]
        } 

        class FrClinicalDocument{

             ClinicalDocument => [None..None]
             ClinicalDocument.realmCode => [1..1]
             ClinicalDocument.typeId => [1..None]
             ClinicalDocument.templateId => [3..None]
             ClinicalDocument.id => [None..None]
             ClinicalDocument.code => [None..None]
             ClinicalDocument.title => [1..None]
             ClinicalDocument.effectiveTime => [None..None]
             ClinicalDocument.confidentialityCode => [None..None]
             ClinicalDocument.languageCode => [1..None]
             ClinicalDocument.setId => [1..None]
             ClinicalDocument.versionNumber => [1..None]
             ClinicalDocument.copyTime => [None..0]
             ClinicalDocument.recordTarget => [None..1]
             ClinicalDocument.author => [None..None]
             ClinicalDocument.dataEnterer => [None..None]
             ClinicalDocument.informant => [None..None]
             ClinicalDocument.custodian => [None..None]
             ClinicalDocument.informationRecipient => [None..None]
             ClinicalDocument.legalAuthenticator => [1..None]
             ClinicalDocument.authenticator => [None..None]
             ClinicalDocument.participant => [None..None]
             ClinicalDocument.inFulfillmentOf => [None..None]
             ClinicalDocument.documentationOf => [1..None]
             ClinicalDocument.relatedDocument => [None..1]
             ClinicalDocument.authorization => [None..None]
             ClinicalDocument.componentOf => [1..None]
        } 

        class FrComponentOf{

             ComponentOf => [None..None]
             ComponentOf.nullFlavor => [None..0]
             ComponentOf.typeId.nullFlavor => [None..0]
             ComponentOf.typeId.assigningAuthorityName => [None..0]
             ComponentOf.typeId.displayable => [None..0]
             ComponentOf.typeCode => [None..0]
             ComponentOf.encompassingEncounter => [None..None]
        } 

        class FrCustodian{

             Custodian.nullFlavor => [None..0]
             Custodian.typeId.nullFlavor => [None..0]
             Custodian.typeId.assigningAuthorityName => [None..0]
             Custodian.typeId.displayable => [None..0]
             Custodian.typeCode => [None..0]
             Custodian.assignedCustodian => [None..None]
        } 

        class FrDataEnterer{

             DataEnterer.nullFlavor => [None..0]
             DataEnterer.typeId.nullFlavor => [None..0]
             DataEnterer.typeId.assigningAuthorityName => [None..0]
             DataEnterer.typeId.displayable => [None..0]
             DataEnterer.typeCode => [None..0]
             DataEnterer.contextControlCode => [None..0]
             DataEnterer.time => [1..None]
             DataEnterer.time.value => [None..None]
             DataEnterer.assignedEntity => [None..None]
        } 

        class FrDocumentationOf{

             DocumentationOf.nullFlavor => [None..0]
             DocumentationOf.typeId.nullFlavor => [None..0]
             DocumentationOf.typeId.assigningAuthorityName => [None..0]
             DocumentationOf.typeId.displayable => [None..0]
             DocumentationOf.typeCode => [None..0]
             DocumentationOf.serviceEvent => [None..None]
        } 

        class FrEncompassingEncounter{

             EncompassingEncounter.typeId.nullFlavor => [None..0]
             EncompassingEncounter.typeId.assigningAuthorityName => [None..0]
             EncompassingEncounter.typeId.displayable => [None..0]
             EncompassingEncounter.classCode => [None..0]
             EncompassingEncounter.moodCode => [None..0]
             EncompassingEncounter.id => [None..None]
             EncompassingEncounter.code => [None..None]
             EncompassingEncounter.code.nullFlavor => [None..0]
             EncompassingEncounter.code.codeSystem => [1..None]
             EncompassingEncounter.code.codeSystemVersion => [None..0]
             EncompassingEncounter.code.displayName => [1..None]
             EncompassingEncounter.code.sdtcValueSet => [None..0]
             EncompassingEncounter.code.sdtcValueSetVersion => [None..0]
             EncompassingEncounter.effectiveTime => [None..None]
             EncompassingEncounter.sdtcAdmissionReferralSourceCode => [None..0]
             EncompassingEncounter.dischargeDispositionCode => [None..None]
             EncompassingEncounter.responsibleParty => [None..None]
             EncompassingEncounter.responsibleParty.nullFlavor => [None..0]
             EncompassingEncounter.responsibleParty.typeId.nullFlavor => [None..0]
             EncompassingEncounter.responsibleParty.typeId.assigningAuthorityName => [None..0]
             EncompassingEncounter.responsibleParty.typeId.displayable => [None..0]
             EncompassingEncounter.encounterParticipant => [None..None]
             EncompassingEncounter.location => [1..None]
             EncompassingEncounter.location.nullFlavor => [None..0]
             EncompassingEncounter.location.typeId.nullFlavor => [None..0]
             EncompassingEncounter.location.typeId.assigningAuthorityName => [None..0]
             EncompassingEncounter.location.typeId.displayable => [None..0]
             EncompassingEncounter.location.typeCode => [None..0]
             EncompassingEncounter.location.healthCareFacility => [None..None]
        } 

        class FrEncounterParticipant{

             EncounterParticipant.typeId.nullFlavor => [None..0]
             EncounterParticipant.typeId.assigningAuthorityName => [None..0]
             EncounterParticipant.typeId.displayable => [None..0]
             EncounterParticipant.typeCode => [None..None]
             EncounterParticipant.time => [None..None]
             EncounterParticipant.assignedEntity => [1..None]
        } 

        class FrHealthCareFacility{

             HealthCareFacility.nullFlavor => [None..0]
             HealthCareFacility.typeId.nullFlavor => [None..0]
             HealthCareFacility.typeId.assigningAuthorityName => [None..0]
             HealthCareFacility.typeId.displayable => [None..0]
             HealthCareFacility.classCode => [None..0]
             HealthCareFacility.id => [None..0]
             HealthCareFacility.sdtcIdentifiedBy => [None..0]
             HealthCareFacility.code => [1..None]
             HealthCareFacility.code.nullFlavor => [None..0]
             HealthCareFacility.code.code => [1..None]
             HealthCareFacility.code.codeSystem => [1..None]
             HealthCareFacility.code.codeSystemVersion => [None..0]
             HealthCareFacility.code.displayName => [1..None]
             HealthCareFacility.code.sdtcValueSet => [None..0]
             HealthCareFacility.code.sdtcValueSetVersion => [None..0]
             HealthCareFacility.code.translation => [None..1]
             HealthCareFacility.code.translation.nullFlavor => [None..0]
             HealthCareFacility.code.translation.code => [1..None]
             HealthCareFacility.code.translation.codeSystem => [1..None]
             HealthCareFacility.code.translation.codeSystemVersion => [None..0]
             HealthCareFacility.code.translation.displayName => [1..None]
             HealthCareFacility.code.translation.sdtcValueSet => [None..0]
             HealthCareFacility.code.translation.sdtcValueSetVersion => [None..0]
             HealthCareFacility.location => [None..None]
        } 

        class FrInFulfillmentOf{

             InFulfillmentOf.typeId.nullFlavor => [None..0]
             InFulfillmentOf.typeId.assigningAuthorityName => [None..0]
             InFulfillmentOf.typeId.displayable => [None..0]
             InFulfillmentOf.typeCode => [None..0]
             InFulfillmentOf.order => [None..None]
        } 

        class FrInformant{

             Informant.nullFlavor => [None..0]
             Informant.typeId.nullFlavor => [None..0]
             Informant.typeId.assigningAuthorityName => [None..0]
             Informant.typeId.displayable => [None..0]
             Informant.typeCode => [None..0]
             Informant.contextControlCode => [None..0]
             Informant.assignedEntity => [None..None]
             Informant.relatedEntity => [None..None]
        } 

        class FrInformationRecipient{

             InformationRecipient.nullFlavor => [None..0]
             InformationRecipient.typeId.nullFlavor => [None..0]
             InformationRecipient.typeId.assigningAuthorityName => [None..0]
             InformationRecipient.typeId.displayable => [None..0]
             InformationRecipient.typeCode => [None..0]
             InformationRecipient.intendedRecipient => [None..None]
        } 

        class FrIntendedRecipient{

             IntendedRecipient.typeId.nullFlavor => [None..0]
             IntendedRecipient.typeId.assigningAuthorityName => [None..0]
             IntendedRecipient.typeId.displayable => [None..0]
             IntendedRecipient.classCode => [None..0]
             IntendedRecipient.id => [None..None]
             IntendedRecipient.id.assigningAuthorityName => [None..0]
             IntendedRecipient.id.displayable => [None..0]
             IntendedRecipient.id.root => [1..None]
             IntendedRecipient.id.extension => [1..None]
             IntendedRecipient.addr => [None..None]
             IntendedRecipient.telecom => [None..None]
             IntendedRecipient.informationRecipient => [None..None]
             IntendedRecipient.receivedOrganization => [None..None]
             IntendedRecipient.receivedOrganization.id.assigningAuthorityName => [None..0]
             IntendedRecipient.receivedOrganization.id.displayable => [None..0]
             IntendedRecipient.receivedOrganization.id.root => [None..None]
        } 

        class FrLegalAuthenticator{

             LegalAuthenticator.nullFlavor => [None..0]
             LegalAuthenticator.typeId.nullFlavor => [None..0]
             LegalAuthenticator.typeId.assigningAuthorityName => [None..0]
             LegalAuthenticator.typeId.displayable => [None..0]
             LegalAuthenticator.typeCode => [None..0]
             LegalAuthenticator.contextControlCode => [None..0]
             LegalAuthenticator.time => [None..None]
             LegalAuthenticator.time.value => [None..None]
             LegalAuthenticator.signatureCode => [None..None]
             LegalAuthenticator.signatureCode.sdtcValueSet => [None..0]
             LegalAuthenticator.signatureCode.sdtcValueSetVersion => [None..0]
             LegalAuthenticator.sdtcSignatureText => [None..0]
             LegalAuthenticator.assignedEntity => [None..None]
             LegalAuthenticator.assignedEntity.code => [None..None]
        } 

        class FrName{

             fr-core-name => [None..None]
             fr-core-name.nullFlavor => [None..0]
             fr-core-name.use => [None..0]
             fr-core-name.item.delimiter => [None..0]
             fr-core-name.item.xmlText => [None..0]
             fr-core-name.validTime => [None..0]
        } 

        class FrOrder{

             Order.nullFlavor => [None..0]
             Order.typeId.nullFlavor => [None..0]
             Order.typeId.assigningAuthorityName => [None..0]
             Order.typeId.displayable => [None..0]
             Order.classCode => [None..0]
             Order.moodCode => [None..0]
             Order.id => [None..None]
             Order.id.nullFlavor => [None..0]
             Order.id.assigningAuthorityName => [None..0]
             Order.id.displayable => [None..0]
             Order.id.root => [1..None]
             Order.id.extension => [None..None]
             Order.code => [None..0]
             Order.priorityCode => [None..0]
        } 

        class FrParentDocument{

             ParentDocument.nullFlavor => [None..0]
             ParentDocument.id => [None..1]
             ParentDocument.id.nullFlavor => [None..0]
             ParentDocument.id.assigningAuthorityName => [None..0]
             ParentDocument.id.displayable => [None..0]
             ParentDocument.id.root => [1..None]
             ParentDocument.id.extension => [None..None]
        } 

        class FrParticipant{

             Participant1.typeId.nullFlavor => [None..0]
             Participant1.typeId.assigningAuthorityName => [None..0]
             Participant1.typeId.displayable => [None..0]
             Participant1.typeCode => [None..None]
             Participant1.contextControlCode => [None..0]
             Participant1.functionCode => [None..None]
             Participant1.functionCode.nullFlavor => [None..0]
             Participant1.functionCode.code => [1..None]
             Participant1.functionCode.codeSystem => [1..None]
             Participant1.functionCode.codeSystemVersion => [None..0]
             Participant1.functionCode.sdtcValueSet => [None..0]
             Participant1.functionCode.sdtcValueSetVersion => [None..0]
             Participant1.functionCode.originalText => [None..None]
             Participant1.time => [1..None]
             Participant1.time.operator => [None..0]
             Participant1.time.low => [None..None]
             Participant1.time.center => [None..0]
             Participant1.time.width => [None..0]
             Participant1.time.high => [None..None]
             Participant1.associatedEntity => [None..None]
        } 

        class FrPatientRole{

             PatientRole.nullFlavor => [None..0]
             PatientRole.realmCode => [None..0]
             PatientRole.typeId => [None..0]
             PatientRole.templateId => [None..0]
             PatientRole.classCode => [None..0]
             PatientRole.id => [None..None]
             PatientRole.id.nullFlavor => [None..0]
             PatientRole.id.assigningAuthorityName => [None..0]
             PatientRole.id.displayable => [None..0]
             PatientRole.id.root => [1..None]
             PatientRole.id.extension => [None..None]
             PatientRole.sdtcIdentifiedBy => [None..0]
             PatientRole.addr => [None..None]
             PatientRole.telecom => [None..None]
             PatientRole.patient => [1..None]
             PatientRole.providerOrganization => [None..0]
        } 

        class FrPatient{

             Patient.nullFlavor => [None..0]
             Patient.typeId.nullFlavor => [None..0]
             Patient.typeId.assigningAuthorityName => [None..0]
             Patient.typeId.displayable => [None..0]
             Patient.determinerCode => [None..0]
             Patient.name => [1..1]
             Patient.name.nullFlavor => [None..0]
             Patient.administrativeGenderCode => [1..None]
             Patient.birthTime => [1..None]
             Patient.sdtcDeceasedInd => [None..None]
             Patient.sdtcDeceasedTime => [None..None]
             Patient.sdtcMultipleBirthInd => [None..None]
             Patient.sdtcMultipleBirthOrderNumber => [None..None]
             Patient.maritalStatusCode => [None..0]
             Patient.religiousAffiliationCode => [None..0]
             Patient.raceCode => [None..0]
             Patient.sdtcRaceCode => [None..0]
             Patient.ethnicGroupCode => [None..0]
             Patient.sdtcEthnicGroupCode => [None..0]
             Patient.guardian => [None..None]
             Patient.birthplace => [None..None]
             Patient.languageCommunication => [None..0]
        } 

        class FrPerformer{

             Performer1.typeId.nullFlavor => [None..0]
             Performer1.typeId.assigningAuthorityName => [None..0]
             Performer1.typeId.displayable => [None..0]
             Performer1.typeCode => [None..None]
             Performer1.functionCode => [None..None]
             Performer1.time => [None..None]
             Performer1.assignedEntity => [None..None]
             Performer1.assignedEntity.code => [None..None]
        } 

        class FrAssignedPerson{

             Person.nullFlavor => [None..0]
             Person.typeId.nullFlavor => [None..0]
             Person.typeId.assigningAuthorityName => [None..0]
             Person.typeId.displayable => [None..0]
             Person.classCode => [None..0]
             Person.determinerCode => [None..0]
             Person.name => [1..1]
             Person.name.item.family => [1..1]
             Person.name.item.given => [None..1]
             Person.name.item.prefix => [None..1]
             Person.name.item.suffix => [None..1]
             Person.sdtcDesc => [None..0]
             Person.sdtcAsPatientRelationship => [None..0]
        } 

        class FrRecordTarget{

             RecordTarget.nullFlavor => [None..0]
             RecordTarget.typeId.nullFlavor => [None..0]
             RecordTarget.typeId.assigningAuthorityName => [None..0]
             RecordTarget.typeId.displayable => [None..0]
             RecordTarget.typeCode => [None..0]
             RecordTarget.contextControlCode => [None..0]
             RecordTarget.patientRole => [None..None]
        } 

        class FrRelatedDocument{

             RelatedDocument.typeId.nullFlavor => [None..0]
             RelatedDocument.typeId.assigningAuthorityName => [None..0]
             RelatedDocument.typeId.displayable => [None..0]
             RelatedDocument.typeCode => [None..None]
             RelatedDocument.parentDocument => [None..None]
        } 

        class FrRelatedEntity{

             RelatedEntity.nullFlavor => [None..0]
             RelatedEntity.typeId.nullFlavor => [None..0]
             RelatedEntity.typeId.assigningAuthorityName => [None..0]
             RelatedEntity.typeId.displayable => [None..0]
             RelatedEntity.classCode => [None..None]
             RelatedEntity.code => [None..None]
             RelatedEntity.code.nullFlavor => [None..0]
             RelatedEntity.code.code => [1..None]
             RelatedEntity.code.codeSystem => [1..None]
             RelatedEntity.code.codeSystemVersion => [None..0]
             RelatedEntity.code.displayName => [1..None]
             RelatedEntity.code.sdtcValueSet => [None..0]
             RelatedEntity.code.sdtcValueSetVersion => [None..0]
             RelatedEntity.addr => [None..None]
             RelatedEntity.telecom => [1..None]
             RelatedEntity.relatedPerson => [1..None]
        } 

        class FrRepresentedCustodianOrganization{

             CustodianOrganization.typeId.nullFlavor => [None..0]
             CustodianOrganization.typeId.assigningAuthorityName => [None..0]
             CustodianOrganization.typeId.displayable => [None..0]
             CustodianOrganization.classCode => [None..0]
             CustodianOrganization.determinerCode => [None..0]
             CustodianOrganization.id => [None..1]
             CustodianOrganization.id.root => [None..None]
             CustodianOrganization.id.extension => [None..None]
             CustodianOrganization.name => [None..None]
             CustodianOrganization.telecom => [None..None]
             CustodianOrganization.sdtcTelecom => [None..0]
             CustodianOrganization.addr => [None..None]
        } 

        class FrRepresentedOrganization{

             Organization.typeId.nullFlavor => [None..0]
             Organization.typeId.assigningAuthorityName => [None..0]
             Organization.typeId.displayable => [None..0]
             Organization.classCode => [None..0]
             Organization.determinerCode => [None..0]
             Organization.id => [None..None]
             Organization.name => [None..None]
             Organization.telecom => [None..None]
             Organization.addr => [None..None]
             Organization.standardIndustryClassCode => [None..None]
             Organization.standardIndustryClassCode.nullFlavor => [None..0]
             Organization.standardIndustryClassCode.code => [None..None]
        } 

        class FrServiceEvent{

             ServiceEvent => [None..None]
             ServiceEvent.nullFlavor => [None..0]
             ServiceEvent.typeId.nullFlavor => [None..0]
             ServiceEvent.typeId.assigningAuthorityName => [None..0]
             ServiceEvent.typeId.displayable => [None..0]
             ServiceEvent.classCode => [None..0]
             ServiceEvent.moodCode => [None..0]
             ServiceEvent.id => [None..None]
             ServiceEvent.code => [None..None]
             ServiceEvent.code.nullFlavor => [None..0]
             ServiceEvent.code.code => [1..None]
             ServiceEvent.code.codeSystem => [1..None]
             ServiceEvent.code.codeSystemVersion => [None..0]
             ServiceEvent.code.displayName => [1..None]
             ServiceEvent.code.sdtcValueSet => [None..0]
             ServiceEvent.code.sdtcValueSetVersion => [None..0]
             ServiceEvent.code.translation => [None..None]
             ServiceEvent.code.translation.nullFlavor => [None..0]
             ServiceEvent.code.translation.codeSystemVersion => [None..0]
             ServiceEvent.code.translation.sdtcValueSet => [None..0]
             ServiceEvent.code.translation.sdtcValueSetVersion => [None..0]
             ServiceEvent.code.translation.qualifier => [None..None]
             ServiceEvent.effectiveTime => [None..None]
             ServiceEvent.effectiveTime.nullFlavor => [None..0]
             ServiceEvent.effectiveTime.operator => [None..0]
             ServiceEvent.effectiveTime.low => [1..None]
             ServiceEvent.effectiveTime.center => [None..0]
             ServiceEvent.effectiveTime.width => [None..0]
             ServiceEvent.effectiveTime.high => [None..None]
             ServiceEvent.performer => [None..1]
             ServiceEvent.performer.nullFlavor => [None..0]
             ServiceEvent.performer.typeCode => [None..None]
        } 

        class FrDeviceDocument{

             Device.identifier => [1..None]
             Device.deviceName => [None..None]
             Device.type => [None..None]
             Device.owner => [1..None]
        } 

        class HumanNameDocument{

             HumanName.use => [None..0]
             HumanName.text => [None..0]
             HumanName.family => [1..None]
             HumanName.given => [None..1]
             HumanName.prefix => [None..1]
             HumanName.suffix => [None..1]
             HumanName.period => [None..0]
        } 

        class FrPatientFHIRDocument{

             Patient => [None..None]
        } 

        class FrPractitionerDocument{

             Practitioner.identifier => [1..None]
             Practitioner.name => [1..1]
             Practitioner.telecom => [None..None]
             Practitioner.address => [None..None]
             Practitioner.qualification => [None..1]
             Practitioner.qualification.code => [None..None]
        } 

        class FrPractitionerRoleDocument{

             PractitionerRole.identifier => [None..0]
             PractitionerRole.active => [None..0]
             PractitionerRole.period => [None..0]
             PractitionerRole.practitioner => [None..None]
             PractitionerRole.organization => [None..None]
             PractitionerRole.code => [None..1]
             PractitionerRole.specialty => [None..0]
             PractitionerRole.location => [None..0]
             PractitionerRole.healthcareService => [None..0]
             PractitionerRole.telecom => [None..0]
             PractitionerRole.availableTime => [None..0]
             PractitionerRole.notAvailable => [None..0]
             PractitionerRole.availabilityExceptions => [None..0]
         }

     }
     package extension #paleturquoise {

     FrCompositionDocument -[#black,dashed,thickness=2]-> DataEnterer
     FrCompositionDocument -[#black,dashed,thickness=2]-> AuthorTime

        class AuthorTime{

          Extension.id => [None..0]
          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class DataEnterer{

          Extension.extension => [3..None]
          Extension.extension:type => [1..1]
          Extension.extension:type.extension => [None..0]
          Extension.extension:type.url => [None..None]
          Extension.extension:type.value[x] => [None..None]
          Extension.extension:type.value[x]:valueCodeableConcept => [0..1]
          Extension.extension:type.value[x]:valueCodeableConcept.coding.system => [None..None]
          Extension.extension:type.value[x]:valueCodeableConcept.coding.code => [None..None]
          Extension.extension:type.value[x]:valueCodeableConcept.text => [None..None]
          Extension.extension:time => [1..1]
          Extension.extension:time.extension => [None..0]
          Extension.extension:time.url => [None..None]
          Extension.extension:time.value[x] => [None..None]
          Extension.extension:time.value[x]:valuePeriod => [0..1]
          Extension.extension:party => [1..1]
          Extension.extension:party.extension => [None..0]
          Extension.extension:party.url => [None..None]
          Extension.extension:party.value[x] => [None..None]
          Extension.extension:party.value[x]:valueReference => [0..1]
          Extension.url => [None..None]
          Extension.value[x] => [None..0]
         }
     }
     package valueset #PaleVioletRed{
       }

package "Ressources de base" #palegreen {

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> AssociationPrescription

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> AssociationPriseEncharge

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> AuteurDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> ConsentementDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> DestinatairePrevuDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> DocumentReference

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> EnteteDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> EvenementDocumente

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> InformateurDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> NonProfessionnelDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> OperateurSaisie

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> ParticipantDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> PatientDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> ProfessionnelAuteurDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> ProfessionnelDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> ResponsableDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> StructureConservationDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> SystemeDocument

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> ValidateurDocument

 class "clinicaldocument" as  class36bd288d6c6ad8dffc41b949ebb77249 

    class36bd288d6c6ad8dffc41b949ebb77249 --> FrCompositionDocument

 class "Organization" as  classd6b258792ff06f82933c74eeb8aef591 

    classd6b258792ff06f82933c74eeb8aef591 --> FrOrganizationDocument

 class "Bundle" as  class94c51f19c37f96ed231f5a0ae512b2a8 

    class94c51f19c37f96ed231f5a0ae512b2a8 --> FrBundleDocument

 class "http://hl7.org/cda/stds/core/StructureDefinition/AssignedAuthor" as  class58510d48686a6398080b7be0a9488a07 

    class58510d48686a6398080b7be0a9488a07 --> FrAssignedAuthor

 class "http://hl7.org/cda/stds/core/StructureDefinition/AssignedCustodian" as  class9d6ae0bd4aff182e6679539d1b5e57dd 

    class9d6ae0bd4aff182e6679539d1b5e57dd --> FrAssignedCustodian

 class "http://hl7.org/cda/stds/core/StructureDefinition/AssignedEntity" as  classa57c2cf8eee922b736f24aae263fb85a 

    classa57c2cf8eee922b736f24aae263fb85a --> FrAssignedEntity

 class "http://hl7.org/cda/stds/core/StructureDefinition/AssociatedEntity" as  classf02f59ca36afce3537fd13cedd8610bc 

    classf02f59ca36afce3537fd13cedd8610bc --> FrAssociatedEntity

 class "http://hl7.org/cda/stds/core/StructureDefinition/Authenticator" as  class53108c7e3b2a59607cdb20ab0b268d03 

    class53108c7e3b2a59607cdb20ab0b268d03 --> FrAuthenticator

 class "http://hl7.org/cda/stds/core/StructureDefinition/Author" as  class937cfe84638a385773bc82a876cf4a8d 

    class937cfe84638a385773bc82a876cf4a8d --> FrAuthor

 class "http://hl7.org/cda/stds/core/StructureDefinition/AuthoringDevice" as  classf46502fb30744212b0c5841a6e4ea035 

    classf46502fb30744212b0c5841a6e4ea035 --> FrAuthoringDevice

 class "http://hl7.org/cda/stds/core/StructureDefinition/Authorization" as  class598114d4c6d4bf797def36d247d40839 

    class598114d4c6d4bf797def36d247d40839 --> FrAuthorization

 class "http://hl7.org/cda/stds/core/StructureDefinition/ClinicalDocument" as  class989be5c5fb811e081805dc5a32645079 

    class989be5c5fb811e081805dc5a32645079 --> FrClinicalDocument

 class "http://hl7.org/cda/stds/core/StructureDefinition/ComponentOf" as  class4277423a305ecb24dc9d37288c280772 

    class4277423a305ecb24dc9d37288c280772 --> FrComponentOf

 class "http://hl7.org/cda/stds/core/StructureDefinition/Custodian" as  classd84e4a39bf094111de7518d5a5411c66 

    classd84e4a39bf094111de7518d5a5411c66 --> FrCustodian

 class "http://hl7.org/cda/stds/core/StructureDefinition/DataEnterer" as  class637494ebd710a0dd928d3bba66f7c36c 

    class637494ebd710a0dd928d3bba66f7c36c --> FrDataEnterer

 class "http://hl7.org/cda/stds/core/StructureDefinition/DocumentationOf" as  class0977267ea48347e7fb26a0e81e862268 

    class0977267ea48347e7fb26a0e81e862268 --> FrDocumentationOf

 class "http://hl7.org/cda/stds/core/StructureDefinition/EncompassingEncounter" as  class71895803bd5b89edafce351523a041e6 

    class71895803bd5b89edafce351523a041e6 --> FrEncompassingEncounter

 class "http://hl7.org/cda/stds/core/StructureDefinition/EncounterParticipant" as  class10428a590ddf9ce27b1fe90b22a362bd 

    class10428a590ddf9ce27b1fe90b22a362bd --> FrEncounterParticipant

 class "http://hl7.org/cda/stds/core/StructureDefinition/HealthCareFacility" as  class02cc646ca5601d63f73402bfbbfdc6eb 

    class02cc646ca5601d63f73402bfbbfdc6eb --> FrHealthCareFacility

 class "http://hl7.org/cda/stds/core/StructureDefinition/InFulfillmentOf" as  classe90f25fe105c3c9c4c47c62629a3765d 

    classe90f25fe105c3c9c4c47c62629a3765d --> FrInFulfillmentOf

 class "http://hl7.org/cda/stds/core/StructureDefinition/Informant" as  class0bdf5ad046cc54eb3cb2ac8f5bc2f2c8 

    class0bdf5ad046cc54eb3cb2ac8f5bc2f2c8 --> FrInformant

 class "http://hl7.org/cda/stds/core/StructureDefinition/InformationRecipient" as  classb6fd1ae4a9b50563c83e48eaaf673af4 

    classb6fd1ae4a9b50563c83e48eaaf673af4 --> FrInformationRecipient

 class "http://hl7.org/cda/stds/core/StructureDefinition/IntendedRecipient" as  classb4c0abb01d11eefbc617aa004a0b6393 

    classb4c0abb01d11eefbc617aa004a0b6393 --> FrIntendedRecipient

 class "http://hl7.org/cda/stds/core/StructureDefinition/LegalAuthenticator" as  class57f35676579cccc1659c4601fa19b43b 

    class57f35676579cccc1659c4601fa19b43b --> FrLegalAuthenticator

 class "http://hl7.org/cda/stds/core/StructureDefinition/PN" as  class91b9b68696e7cdd4a91365aa0d0d170c 

    class91b9b68696e7cdd4a91365aa0d0d170c --> FrName

 class "http://hl7.org/cda/stds/core/StructureDefinition/Order" as  class358c910e07ad3f95a61b1dae6d4a35be 

    class358c910e07ad3f95a61b1dae6d4a35be --> FrOrder

 class "http://hl7.org/cda/stds/core/StructureDefinition/ParentDocument" as  class4313f3b50ac00c5473aecb642b99f6e4 

    class4313f3b50ac00c5473aecb642b99f6e4 --> FrParentDocument

 class "http://hl7.org/cda/stds/core/StructureDefinition/Participant1" as  class2fd9a3b182710aa68f9e615904fe1537 

    class2fd9a3b182710aa68f9e615904fe1537 --> FrParticipant

 class "http://hl7.org/cda/stds/core/StructureDefinition/PatientRole" as  class1e213e8519f12110736b032cda341174 

    class1e213e8519f12110736b032cda341174 --> FrPatientRole

 class "http://hl7.org/cda/stds/core/StructureDefinition/Patient" as  classa8889bb6f3999fb5243b3ed3b492e0c4 

    classa8889bb6f3999fb5243b3ed3b492e0c4 --> FrPatient

 class "http://hl7.org/cda/stds/core/StructureDefinition/Performer1" as  class2322ea8c73e0b95c4de59f56ee36a694 

    class2322ea8c73e0b95c4de59f56ee36a694 --> FrPerformer

 class "http://hl7.org/cda/stds/core/StructureDefinition/Person" as  classb14b9f756425869ebeb8ade0004931e1 

    classb14b9f756425869ebeb8ade0004931e1 --> FrAssignedPerson

 class "http://hl7.org/cda/stds/core/StructureDefinition/RecordTarget" as  class0baedfe5573df35f7a6ee5934c45b818 

    class0baedfe5573df35f7a6ee5934c45b818 --> FrRecordTarget

 class "http://hl7.org/cda/stds/core/StructureDefinition/RelatedDocument" as  classddc7c43262268f3e7ef73c1c5ad6b514 

    classddc7c43262268f3e7ef73c1c5ad6b514 --> FrRelatedDocument

 class "http://hl7.org/cda/stds/core/StructureDefinition/RelatedEntity" as  class0a3bfa693dae125e5c0a4e8cab321d9a 

    class0a3bfa693dae125e5c0a4e8cab321d9a --> FrRelatedEntity

 class "http://hl7.org/cda/stds/core/StructureDefinition/CustodianOrganization" as  class958e4615d47e79ed7eef2368401c733a 

    class958e4615d47e79ed7eef2368401c733a --> FrRepresentedCustodianOrganization

 class "http://hl7.org/cda/stds/core/StructureDefinition/Organization" as  class70defb4802516f8b110654a1e3649ed7 

    class70defb4802516f8b110654a1e3649ed7 --> FrRepresentedOrganization

 class "http://hl7.org/cda/stds/core/StructureDefinition/ServiceEvent" as  class21fc45b6eacaebf264ceab7c3130a980 

    class21fc45b6eacaebf264ceab7c3130a980 --> FrServiceEvent

 class "Device" as  classe0ac20adce6ffee48c7151b070aa5737 

    classe0ac20adce6ffee48c7151b070aa5737 --> FrDeviceDocument

 class "HumanName" as  class95e0fecbaf28f967a098167115412fc6 

    class95e0fecbaf28f967a098167115412fc6 --> HumanNameDocument

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-patient" as  classcb72a5551de902d7716887df67489a97 

    classcb72a5551de902d7716887df67489a97 --> FrPatientFHIRDocument

 class "Practitioner" as  classe1fdce734a2fd9596ad930bdb139ca06 

    classe1fdce734a2fd9596ad930bdb139ca06 --> FrPractitionerDocument

 class "PractitionerRole" as  classa6482460b0b027d14fe848816788acb6 

    classa6482460b0b027d14fe848816788acb6 --> FrPractitionerRoleDocument
}
@enduml